export const MOCKUP_NOTE =
  'Mockup — sample data for client review. Nothing is saved.';

export const SAMPLE_PAYOUTS = [
  {
    id: 'po-12345',
    orderId: '12345',
    plant: 'Philodendron Jennifer',
    variegation: 'Variegated',
    potSize: '6"',
    liveSaleDate: 'Aug 10, 2026',
    orderDate: 'Aug 10, 2026',
    scanDate: 'Aug 12, 2026',
    listedPrice: 200,
    commissionRate: 10,
    commission: 20,
    logistics: 20,
    plantCare: 5,
    netPayout: 155,
    paymentStatus: 'Paid',
    payoutStatus: 'Receivable',
    businessName: 'Greenleaf Garden',
    country: 'Philippines',
  },
  {
    id: 'po-12346',
    orderId: '12346',
    plant: 'Monstera Thai Constellation',
    variegation: 'Thai Constellation',
    potSize: '4"',
    liveSaleDate: 'Aug 10, 2026',
    orderDate: 'Aug 10, 2026',
    scanDate: 'Aug 12, 2026',
    listedPrice: 175,
    commissionRate: 10,
    commission: 17.5,
    logistics: 15,
    plantCare: 5,
    netPayout: 137.5,
    paymentStatus: 'Paid',
    payoutStatus: 'Receivable',
    businessName: 'Greenleaf Garden',
    country: 'Philippines',
  },
  {
    id: 'po-12350',
    orderId: '12350',
    plant: 'Anthurium Crystallinum',
    variegation: '',
    potSize: '2"',
    liveSaleDate: 'Aug 17, 2026',
    orderDate: 'Aug 17, 2026',
    scanDate: '—',
    listedPrice: 90,
    commissionRate: 8,
    commission: 7.2,
    logistics: 15,
    plantCare: 5,
    netPayout: 62.8,
    paymentStatus: 'Paid',
    payoutStatus: 'Receivable',
    businessName: 'Greenleaf Garden',
    country: 'Philippines',
  },
];

export const SAMPLE_LISTINGS = [
  {
    id: 'l1',
    genus: 'Philodendron',
    species: 'Jennifer',
    variegation: 'Variegated',
    status: 'Live',
    pin: false,
    listingType: 'Live',
    price: '200.00',
    potSize: '6"',
    height: 'Above',
  },
  {
    id: 'l2',
    genus: 'Monstera',
    species: 'Thai Constellation',
    variegation: 'Thai Constellation',
    status: 'Live',
    pin: true,
    listingType: 'Live',
    price: '175.00',
    potSize: '4"',
    height: 'Below',
  },
  {
    id: 'l3',
    genus: 'Anthurium',
    species: 'Crystallinum',
    variegation: '',
    status: 'Inactive',
    pin: false,
    listingType: 'Group Chat',
    price: '90.00',
    potSize: '2"',
    height: 'Below',
  },
  {
    id: 'l4',
    genus: 'Alocasia',
    species: 'Dragon Scale',
    variegation: '',
    status: 'Live',
    pin: false,
    listingType: 'Live',
    price: '65.00',
    potSize: '4"',
    height: 'Above',
  },
];

export const SAMPLE_REQUESTS = [
  {
    id: 'req-1',
    name: 'Maya Chen',
    email: 'maya.chen@email.com',
    fromType: 'US Customer',
    toType: 'US Business',
    country: 'United States',
    gardenName: 'Maya Live Plants',
    submittedAt: 'Aug 14, 2026',
    status: 'Pending',
    notes: 'Wants Live Selling only. Will keep buying as a customer.',
  },
  {
    id: 'req-2',
    name: 'Luis Santos',
    email: 'luis@greenleaf.ph',
    fromType: 'Asia Seller',
    toType: 'Asia Business',
    country: 'Philippines',
    gardenName: 'Greenleaf Garden',
    submittedAt: 'Aug 13, 2026',
    status: 'Pending',
    notes: 'Existing live seller switching to USD + commission model.',
  },
  {
    id: 'req-3',
    name: 'Siti Rahman',
    email: 'siti@tropica.id',
    fromType: 'Asia Seller',
    toType: 'Asia Business',
    country: 'Indonesia',
    gardenName: 'Tropica ID',
    submittedAt: 'Aug 8, 2026',
    status: 'Approved',
    notes: 'Approved. New listings use exact USD.',
  },
];

export const SAMPLE_FEE_CONFIG = {
  defaults: {
    commissionPercent: 10,
    logisticsSmall: 15,
    logisticsLarge: 20,
    plantCare: 5,
    applyLogistics: true,
    applyPlantCare: true,
  },
  byCountry: [
    {country: 'Philippines', commissionPercent: 10},
    {country: 'Thailand', commissionPercent: 10},
    {country: 'Indonesia', commissionPercent: 10},
    {country: 'Singapore', commissionPercent: 8},
    {country: 'Vietnam', commissionPercent: 10},
    {country: 'Taiwan', commissionPercent: 10},
    {country: 'United States', commissionPercent: 10},
  ],
  byBusiness: [
    {name: 'Greenleaf Garden', country: 'Philippines', commissionPercent: 10},
    {name: 'Tropica ID', country: 'Indonesia', commissionPercent: 8},
  ],
};

export const SAMPLE_US_BUYER = {
  firstName: 'Maya',
  lastName: 'Chen',
  email: 'maya.chen@email.com',
  username: 'mayachen',
  phone: '+1 (415) 555-0188',
  accountClass: 'US Customer',
  status: 'Active',
  address: '1842 Oak Street',
  city: 'San Francisco',
  state: 'California',
  zipCode: '94117',
  country: 'United States',
  leafPoints: 240,
  plantCredits: 15,
  shippingCredits: 2,
  canBuy: true,
  canLiveSell: false,
  canMainstreamSell: false,
};

export const formatUsd = value => {
  const n = Number(value);
  if (Number.isNaN(n)) {
    return '$0.00';
  }
  return `$${n.toFixed(2)}`;
};
