import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  myCurrentOrdersSection: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    paddingHorizontal: 24,
    paddingVertical: 12,
    gap: 12,
    width: '100%',
  },
  myCurrentOrdersTitle: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 16,
    lineHeight: 24,
    color: '#393D40',
    flex: 1,
  },
  detailsSection: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    paddingHorizontal: 24,
    paddingVertical: 12,
    gap: 12,
    width: '100%',
    minHeight: 324,
  },
  detailsTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 0,
    gap: 6,
    width: 327,
    height: 24,
    alignSelf: 'stretch',
  },
  detailsTitle: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 16,
    lineHeight: 24,
    color: '#393D40',
    flex: 1,
  },
  detailRowOrder: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: 0,
    gap: 12,
    width: 327,
    height: 24,
    alignSelf: 'stretch',
  },
  detailContentOrder: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: 0,
    gap: 2,
    flex: 1,
    width: 291,
    height: 24,
  },
  detailTextRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 0,
    gap: 4,
    width: 291,
    height: 24,
    alignSelf: 'stretch',
  },
  detailData: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 24,
    color: '#202325',
    flex: 1,
  },
  viewOrdersLink: {
    padding: 0,
    gap: 4,
    width: 96,
    height: 22,
  },
  viewOrdersText: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 22,
    color: '#539461',
    textAlign: 'center',
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: 0,
    gap: 12,
    width: 327,
    height: 48,
    alignSelf: 'stretch',
  },
  detailContent: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: 0,
    gap: 2,
    flex: 1,
    width: 291,
    height: 48,
  },
  detailLabel: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 22,
    color: '#647276',
    width: 291,
    height: 22,
  },
  dividerContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    paddingVertical: 8,
    width: '100%',
    height: 28,
  },
  divider: {
    width: '100%',
    height: 12,
    backgroundColor: '#F5F6F6',
  },
  approvedNoteContainer: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    paddingHorizontal: 24,
    paddingVertical: 12,
    gap: 8,
    width: '100%',
    minHeight: 220,
  },
  approvedNoteBold: {
    width: 327,
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 14,
    lineHeight: 20,
    color: '#647276',
    alignSelf: 'stretch',
    flexWrap: 'wrap',
  },
  approvedNoteText: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 14,
    lineHeight: 20,
    color: '#647276',
    alignSelf: 'stretch',
    flexWrap: 'wrap',
  },
  actionContainer: {
    flexDirection: 'column',
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 12,
    gap: 24,
    width: '100%',
    height: 84,
  },
  cancelButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 12,
    width: 327,
    height: 48,
    minHeight: 48,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CDD3D4',
    borderRadius: 12,
  },
  cancelButtonText: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 16,
    color: '#393D40',
    textAlign: 'center',
  },
  pendingCancelButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 12,
    width: 327,
    height: 48,
    minHeight: 48,
    backgroundColor: '#DC3545',
    borderWidth: 1,
    borderColor: '#DC3545',
    borderRadius: 12,
  },
  pendingCancelButtonText: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 16,
    color: '#FFFFFF',
    textAlign: 'center',
  },
});

export default styles;

