import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  emptyStateContainer: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    paddingTop: 50,
    paddingBottom: 34,
    width: '100%',
    flex: 1,
  },
  iconSection: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: 24,
    paddingVertical: 12,
    width: '100%',
    height: 120,
    justifyContent: 'flex-start',
  },
  titleSection: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    paddingHorizontal: 24,
    paddingVertical: 16,
    gap: 12,
    width: '100%',
    height: 96,
  },
  titleText: {
    width: 280,
    height: 64,
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 28,
    lineHeight: 32,
    color: '#202325',
    textAlignVertical: 'center',
  },
  noteSection: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    paddingHorizontal: 24,
    paddingVertical: 12,
    gap: 12,
    width: '100%',
    height: 212,
  },
  noteText: {
    width: 327,
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 22,
    color: '#393D40',
    alignSelf: 'stretch',
  },
  addressSection: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: 24,
    gap: 16,
    width: '100%',
    height: 190,
  },
  inputContainer: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    gap: 8,
    width: 327,
    height: 78,
    alignSelf: 'stretch',
  },
  inputLabel: {
    width: 327,
    height: 22,
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 22,
    color: '#393D40',
    alignSelf: 'stretch',
  },
  inputPressable: {
    width: 327,
    alignSelf: 'stretch',
  },
  textInput: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
    width: 327,
    height: 48,
    minHeight: 48,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CDD3D4',
    borderRadius: 12,
    justifyContent: 'flex-start',
  },
  textInputText: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 22,
    color: '#202325',
  },
  textInputPlaceholder: {
    color: '#647276',
  },
  createButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 12,
    width: 327,
    height: 48,
    minHeight: 48,
    backgroundColor: '#539461',
    borderRadius: 12,
  },
  createButtonDisabled: {
    opacity: 0.6,
  },
  createButtonText: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 16,
    color: '#FFFFFF',
  },
});

export default styles;

