import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: 340,
    minHeight: 154,
    alignItems: 'flex-start',
    padding: 0,
    gap: 16,
  },
  popover: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    paddingTop: 16,
    paddingLeft: 0,
    paddingRight: 0,
    paddingBottom: 0,
    width: 340,
    minHeight: 98,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CDD3D4',
    borderRadius: 12,
  },
  textContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingBottom: 16,
    gap: 12,
    width: 340,
    minHeight: 82,
  },
  emojiIcon: {
    fontSize: 32,
    marginBottom: 4,
  },
  titleText: {
    width: 292,
    minHeight: 66,
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 22, // 140% of 16px
    textAlign: 'center',
    color: '#202325',
    flexShrink: 1,
  },
  actionContainer: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: 0,
    width: 340,
    minHeight: 48,
  },
  confirmButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 24,
    width: 340,
    minHeight: 48,
    marginTop: 20,
    backgroundColor: '#393D40',
    borderRadius: 12,
  },
  confirmButtonText: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 16,
    color: '#FFFFFF',
  },
  // Keep legacy button styles for backward compatibility
  cancelButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 24,
    width: 340,
    minHeight: 48,
    backgroundColor: '#F5F6F6',
    borderRadius: 12,
  },
  cancelButtonText: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 16,
    color: '#FFFFFF',
  },
});

export default styles;

