import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  joinerCard: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    paddingVertical: 6,
    paddingHorizontal: 12,
    gap: 12,
    width: '100%',
    backgroundColor: '#F5F6F6',
  },
  joinerUserCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: 12,
    gap: 12,
    width: 351,
    minHeight: 76,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    alignSelf: 'stretch',
  },
  joinerAvatarContainer: {
    width: 40,
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: 0,
    gap: 10,
    alignSelf: 'flex-start',
  },
  joinerAvatar: {
    width: 40,
    height: 40,
    minWidth: 40,
    minHeight: 40,
    borderRadius: 1000,
    borderWidth: 1,
    borderColor: '#539461',
    overflow: 'hidden',
  },
  joinerAvatarImage: {
    width: '100%',
    height: '100%',
  },
  joinerAvatarPlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: '#DFECDF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  joinerAvatarText: {
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: '600',
    color: '#539461',
  },
  joinerContent: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: 0,
    gap: 4,
    flex: 1,
    width: 275,
    minHeight: 52,
  },
  joinerNameRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 4,
    width: 275,
    height: 24,
    alignSelf: 'stretch',
  },
  joinerName: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 18,
    lineHeight: 24,
    color: '#202325',
    height: 24,
  },
  joinerUsername: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 22,
    color: '#7F8D91',
    flex: 1,
    flexWrap: 'wrap',
  },
  expirationDateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 0,
    gap: 4,
    width: 275,
    height: 24,
    alignSelf: 'stretch',
  },
  expirationDateText: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 22,
    color: '#647276',
    width: 164,
    height: 22,
  },
  requestSection: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: 0,
    gap: 12,
    alignSelf: 'stretch',
  },
  requestLabel: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 22,
    color: '#393D40',
  },
  requestLabelCancel: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 22,
    color: '#DC3545',
  },
  requestSectionCancel: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 0,
    gap: 12,
    alignSelf: 'stretch',
  },
  iconButtonsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  iconButtonApprove: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#539461',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconButtonReject: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#414649',
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    alignSelf: 'stretch',
  },
  approveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    gap: 8,
    flex: 1,
    height: 40,
    backgroundColor: '#539461',
    borderRadius: 12,
  },
  approveButtonText: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 16,
    color: '#FFFFFF',
    width: 58,
    height: 16,
  },
  rejectButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    gap: 8,
    flex: 1,
    height: 40,
    backgroundColor: '#414649',
    borderRadius: 12,
  },
  rejectButtonText: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 16,
    color: '#FFFFFF',
    width: 58,
    height: 16,
  },
});

export default styles;

