import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: 12,
    backgroundColor: '#DFECDF',
  },
  backButton: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 18,
    lineHeight: 22,
    color: '#202325',
    marginLeft: -24,
  },
  headerSpacer: {
    width: 24,
    height: 24,
  },
  content: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scrollContentContainer: {
    paddingBottom: 34,
    minHeight: 812,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
  },
  requesterContainer: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    paddingTop: 30,
    paddingBottom: 34,
    width: '100%',
    flex: 1,
  },
  buddyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 12,
    gap: 12,
    width: '100%',
    height: 88,
  },
  buddyAvatar: {
    width: 64,
    minWidth: 64,
    height: 64,
    minHeight: 64,
    borderRadius: 1000,
    borderWidth: 1,
    borderColor: '#539461',
    overflow: 'hidden',
  },
  buddyAvatarImage: {
    width: '100%',
    height: '100%',
  },
  buddyAvatarPlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: '#DFECDF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buddyAvatarText: {
    fontFamily: 'Inter',
    fontSize: 24,
    fontWeight: '700',
    color: '#539461',
  },
  buddyDetails: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: 0,
    gap: 4,
    flex: 1,
    minHeight: 50,
  },
  buddyName: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 20,
    lineHeight: 24,
    color: '#202325',
    flexShrink: 1,
    width: '100%',
  },
  buddyUsername: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 22,
    color: '#7F8D91',
    flexShrink: 1,
    width: '100%',
  },
  dividerContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    paddingVertical: 8,
    width: '100%',
    height: 28,
  },
  divider: {
    width: '100%',
    height: 12,
    backgroundColor: '#F5F6F6',
  },
  statusContainer: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    paddingHorizontal: 24,
    paddingVertical: 12,
    gap: 12,
    width: '100%',
    height: 46,
  },
  statusLabel: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 22,
    color: '#539461',
    width: 327,
    height: 22,
  },
  actionContainer: {
    flexDirection: 'column',
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 12,
    gap: 24,
    width: '100%',
    height: 84,
  },
  cancelButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 12,
    width: 327,
    height: 48,
    minHeight: 48,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CDD3D4',
    borderRadius: 12,
  },
  cancelButtonText: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 16,
    color: '#393D40',
    textAlign: 'center',
  },
  noteContainer: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    paddingHorizontal: 24,
    paddingVertical: 12,
    gap: 8,
    width: '100%',
    minHeight: 64,
    borderRadius: 0,
    alignSelf: 'stretch',
    flexGrow: 0,
  },
  noteText: {
    flex: 1,
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 22,
    color: '#393D40',
    alignSelf: 'stretch',
    flexWrap: 'wrap',
  },
});

export default styles;

