import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  paymentMethod: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  paymentMethodRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  paymentMethodTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
  },
  paymentOptionText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#6B7280',
  },
  paymentDivider: {
    marginBottom: 16,
  },
  paymentDividerLine: {
    height: 1,
    backgroundColor: '#E5E7EB',
  },
  summary: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  quantity: {
    marginBottom: 16,
  },
  quantityTitle: {
    marginBottom: 12,
  },
  quantityTitleText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
  },
  quantityContent: {
    gap: 8,
  },
  singleGrowerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  wholesaleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  growersChoiceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  quantityTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  quantityTotalLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
  },
  quantityTotalNumber: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
  },
  summaryDivider: {
    marginVertical: 16,
  },
  dividerLine: {
    height: 1,
    backgroundColor: '#E5E7EB',
  },
  subtotal: {
    marginBottom: 16,
  },
  plantCostRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  priceComparisonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  originalPriceStrikethrough: {
    fontSize: 16,
    fontWeight: '500',
    color: '#9CA3AF',
    textDecorationLine: 'line-through',
  },
  discountedPriceFinal: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
  },
  subtotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  subtotalLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: '#6B7280',
  },
  subtotalNumber: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
  },
  shippingCreditsNotification: {
    backgroundColor: '#F0FDF4',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
  },
  shippingCreditsNotificationText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#059669',
    textAlign: 'center',
  },
  shippingSummary: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    paddingHorizontal: 5,
    paddingVertical: 0,
    gap: 8,
    width: '100%',
    alignSelf: 'stretch',
  },
  shippingSummaryTitle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 0,
    gap: 10,
    width: '100%',
    height: 24,
  },
  shippingSummaryTitleText: {
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 24,
    color: '#202325',
    width: '100%',
    textAlign: 'left',
  },
  shippingSummaryContent: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: 0,
    gap: 6,
    width: '100%',
  },
  shippingFeeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 0,
    width: '100%',
    height: 22,
    alignSelf: 'stretch',
  },
  baseAirCargoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 0,
    width: '100%',
    height: 28,
    alignSelf: 'stretch',
  },
  wholesaleAirCargoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 0,
    width: '100%',
    height: 22,
    alignSelf: 'stretch',
  },
  airCargoCreditRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  airCargoCreditAmount: {
    fontSize: 16,
    fontWeight: '600',
    color: '#059669',
  },
  shippingCreditsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 0,
    width: '100%',
    height: 22,
    alignSelf: 'stretch',
  },
  shippingCreditsLabel: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 22,
    color: '#647276',
    width: 195,
    height: 22,
  },
  shippingCreditsAmount: {
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 22,
    color: '#E7522F',
    width: 48,
    height: 22,
    textAlign: 'right',
  },
  shippingTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 0,
    width: '100%',
    height: 24,
    alignSelf: 'stretch',
  },
  shippingTotalLabel: {
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 22,
    color: '#202325',
    flex: 1,
  },
  shippingTotalNumber: {
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 24,
    color: '#202325',
    textAlign: 'right',
  },
  labeledToggle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 0,
    gap: 4,
    width: '100%',
    height: 24,
    alignSelf: 'stretch',
  },
  toggleLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 0,
    gap: 12,
    flex: 1,
    height: 22,
  },
  toggleLabelText: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 22,
    color: '#647276',
    flex: 1,
    height: 22,
  },
  summaryRowLabel: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 22,
    color: '#647276',
    flex: 1,
  },
  summaryRowNumber: {
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 22,
    color: '#202325',
    textAlign: 'right',
  },
  baseAirCargoLabelContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 0,
    width: 142,
    height: 28,
  },
  baseAirCargoLabel: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 22,
    color: '#647276',
    width: 114,
    height: 22,
  },
  baseAirCargoTooltip: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: 0,
    width: 28,
    height: 28,
  },
  baseAirCargoTooltipIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 4,
    gap: 10,
    width: 28,
    height: 28,
  },
  baseAirCargoAmount: {
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 22,
    color: '#202325',
    height: 22,
    textAlign: 'right',
  },
  wholesaleAirCargoLabel: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 22,
    color: '#647276',
    flex: 1,
    height: 22,
  },
  wholesaleAirCargoNumber: {
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 22,
    color: '#202325',
    height: 22,
    textAlign: 'right',
  },
  formToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 0,
    gap: 8,
    alignSelf: 'center',
    minWidth: 99,
    height: 24,
    minHeight: 24,
    flexShrink: 0,
  },
  toggleText: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 0,
    gap: 4,
  },
  upsToggleText: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 0,
    gap: 4,
    minWidth: 47,
    height: 22,
    flexShrink: 0,
  },
  upsToggleLabel: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 22,
    color: '#A9B3B7',
    width: 11,
    height: 22,
  },
  upsToggleLabelOff: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 22,
    color: '#A9B3B7',
    width: 11,
    height: 22,
  },
  upsToggleNumber: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 22,
    color: '#A9B3B7',
    minWidth: 40,
    height: 22,
    flexShrink: 0,
  },
  upsToggleNumberOff: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 22,
    color: '#A9B3B7',
    minWidth: 40,
    height: 22,
    flexShrink: 0,
  },
  toggleOnLabel: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 22,
    color: '#393D40',
    width: 30,
  },
  toggleOffLabel: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 22,
    color: '#393D40',
    width: 30,
  },
  toggleOnNumber: {
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 22,
    color: '#393D40',
  },
  toggleOffNumber: {
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 22,
    color: '#393D40',
  },
  switchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 2,
    gap: 10,
    width: 44,
    maxWidth: 44,
    height: 24,
    maxHeight: 24,
    backgroundColor: '#7F8D91',
    borderRadius: 32,
  },
  switchContainerActive: {
    backgroundColor: '#539461',
  },
  switchKnob: {
    width: 20,
    height: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 1000,
  },
  switchKnobActive: {
    transform: [{ translateX: 20 }],
  },
  points: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    paddingHorizontal: 5,
    paddingVertical: 0,
    gap: 8,
    width: '100%',
    alignSelf: 'stretch',
  },
  pointsTitle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 0,
    gap: 10,
    width: '100%',
    height: 48,
  },
  pointsTitleText: {
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 24,
    color: '#202325',
    width: '100%',
    textAlign: 'left',
  },
  pointOptions: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    paddingVertical: 8,
    paddingHorizontal: 0,
    gap: 12,
    width: '100%',
  },
  discountOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 4,
    paddingHorizontal: 0,
    gap: 4,
    width: '100%',
    height: 36,
    alignSelf: 'stretch',
  },
  discountInputSection: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 4,
    paddingHorizontal: 0,
    gap: 8,
    width: '100%',
    height: 56,
    alignSelf: 'stretch',
  },
  discountTextField: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    padding: 0,
    gap: 8,
    flex: 1,
    height: 48,
  },
  textFieldContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    gap: 12,
    width: '100%',
    height: 48,
    minHeight: 48,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CDD3D4',
    borderRadius: 12,
  },
  textFieldIcon: {
    width: 24,
    height: 24,
  },
  textFieldInput: {
    flex: 1,
    height: 22,
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 22,
    color: '#647276',
    padding: 0,
  },
  discountApplyButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 12,
    width: 85,
    height: 48,
    minHeight: 48,
    backgroundColor: '#539461',
    borderRadius: 12,
  },
  discountApplyButtonText: {
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 16,
    color: '#FFFFFF',
    paddingHorizontal: 8,
  },
  plantCreditsOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 4,
    paddingHorizontal: 0,
    gap: 4,
    width: '100%',
    height: 36,
    alignSelf: 'stretch',
  },
  shippingCreditsOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 4,
    paddingHorizontal: 0,
    gap: 4,
    width: '100%',
    height: 36,
    alignSelf: 'stretch',
  },
  iconLabelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 0,
    gap: 8,
    alignSelf: 'center',
  },
  leafIconLabelContainer: {
    width: 131,
    height: 36,
  },
  plantIconLabelContainer: {
    width: 144,
    height: 36,
  },
  shippingIconLabelContainer: {
    width: 173,
    height: 36,
  },
  iconContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 6,
    gap: 8,
    width: 36,
    height: 36,
    borderRadius: 1000,
  },
  leafIconContainer: {
    backgroundColor: '#539461',
  },
  plantIconContainer: {
    backgroundColor: '#6B4EFF',
  },
  shippingIconContainer: {
    backgroundColor: '#48A7F8',
  },
  iconLabel: {
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 22,
    color: '#202325',
  },
  leafIconLabel: {
    width: 87,
    height: 22,
  },
  plantIconLabel: {
    width: 100,
    height: 22,
  },
  shippingIconLabel: {
    width: 129,
    height: 22,
  },
  toggle: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 0,
    gap: 8,
    height: 24,
    minHeight: 24,
  },
  finalTotal: {
    marginTop: 16,
  },
  finalTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 16,
    borderTopWidth: 2,
    borderTopColor: '#E5E7EB',
  },
  finalTotalLabel: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
  },
  finalTotalNumber: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
  },
  // Skeleton styles
  skeletonText: {
    height: 16,
    width: 120,
    backgroundColor: '#E5E7EB',
    borderRadius: 4,
  },
  skeletonTextShort: {
    height: 16,
    width: 80,
    backgroundColor: '#E5E7EB',
    borderRadius: 4,
  },
  skeletonTextTotal: {
    height: 18,
    width: 140,
    backgroundColor: '#E5E7EB',
    borderRadius: 4,
  },
  skeletonAmount: {
    height: 16,
    width: 60,
    backgroundColor: '#E5E7EB',
    borderRadius: 4,
  },
  skeletonAmountLarge: {
    height: 18,
    width: 80,
    backgroundColor: '#E5E7EB',
    borderRadius: 4,
  },
  skeletonToggle: {
    height: 24,
    width: 44,
    backgroundColor: '#E5E7EB',
    borderRadius: 12,
  },
});

export default styles;
